[package]
name = "virtfs-ach"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.1"
signature = "1.3.1"
lz4_flex = "0.8.2"
rand = "0.7.0"
