[package]
name = "vach"
version = "0.1.0"
edition = "2018"

# TODO: Rename paths to IDs
# 		Replace keypair with generic
# 		Archives don't need to be mutable to allow reading, use Rc
#		Resource to not store the data in a vector rather they store it in an impl Read
# 		impl Iter and Stream dunctionality for Archives

[dependencies]
anyhow = "1.0.42"
ed25519-dalek = "1.0.1"
lz4_flex = "0.8.2"
rand = "0.8.4"
hashbrown = "0.11.2"
bitflags = "1.3.2"