fn_args_layout = "Compressed"
brace_style = "PreferSameLine"
hard_tabs = true
reorder_imports = false
indent_style = "Block"
struct_lit_single_line = true
max_width = 120
match_block_trailing_comma = true
use_field_init_shorthand = true
attr_fn_like_width = 130
