[package]
name = "vach-cli"
version = "0.3.3"
edition = "2021"
authors = [
	"Jasper Fortuin <zeskeertwee@gmail.com>",
	" Newton Toto <nyachiengatoto@gmail.com>",
]
description = "A command-line tool to work with .vach files"
license = "MIT"
repository = "https://github.com/zeskeertwee/vach"
categories = ["command-line-utilities", "encoding", "game-development"]
keywords = ["archive", "command-line", "vach", "assets", "game"]
readme = "README.md"
include = ["src/*", "Cargo.toml", "../README.md"]

[[bin]]
name = "vach"
path = "src/main.rs"

[dependencies]
indicatif = "0.16.2"
clap = "3.0.5"
anyhow = "1.0.44"
tabled = "0.4.0"
log = "0.4.14"
vach2 = { package = "vach", version = "0.2" }
walkdir = "2.3.2"
bytesize = "1.1.0"

[profile.release]
lto = true
