[package]
name = "vach"
version = "0.1.9"
edition = "2021"
authors = ["Jasper Fortuin <zeskeertwee@gmail.com>", "Newton Toto <nyachiengatoto@gmail.com>"]
description = "A simple archiving format, designed for storing assets in compact secure containers"
license = "GPL-2.0"
repository = "https://github.com/zeskeertwee/virtfs-rs"
categories = [
	"games",
	"compression"
]
keywords = [
	"archive",
	"filesystem",
	"compression",
	"game",
	"assets"
]
documentation = "https://docs.rs/vach"
readme = "../README.md"
include = [
	"Cargo.toml",
	"src/*",
	"../README.md"
]

[dependencies]
anyhow = "1.0.44"
ed25519-dalek = "1.0.1"
lz4_flex = "0.9.0"
rand = "0.7.0"
hashbrown = "0.11.2"
chacha20stream = "2.2.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmark"
harness = false
path = "benches/benchmark.rs"