[package]
name = "vach"

# NOTE: Make sure spec.txt and vach::VERSION constants are all synced up
version = "0.3.2"

edition = "2021"
authors = [
	"Jasper Fortuin <zeskeertwee@gmail.com>",
	"Newton Toto <nyachiengatoto@gmail.com>",
]
description = "A simple archiving format, designed for storing assets in compact secure containers"
license = "MIT"
repository = "https://github.com/zeskeertwee/vach"
categories = ["games", "compression"]
keywords = ["archive", "filesystem", "compression", "game", "assets"]
documentation = "https://docs.rs/vach"
readme = "README.md"
include = ["Cargo.toml", "Cargo.lock", "src/*"]

[dependencies]
ed25519-dalek = "1.0.1"
lz4_flex = "0.9.0"
rand = "0.7.0"
aes-gcm-siv = "0.10.3"
snap = "1.0.5"
brotli = "3.3.2"
rayon = { version = "1.5.1", optional = true }

[features]
multithreaded = ["rayon"]
