[package]
name = "vach"
version = "0.1.3"
edition = "2018"
authors = ["Jasper Fortuin <zeskeertwee@gmail.com>", "Newton Toto <nyachiengatoto@gmail.com>"]
description = "A simple archiving format, designed for storing assets in compact secure containers"
license = "GPL-2.0"
homepage = "https://github.com/zeskeertwee/virtfs-rs"
categories = [
	"parsing",
	"games",
	"compression"
]
keywords = [
	"archive",
	"secure",
	"storage",
	"vach",
	"format"
]
documentation = "https://docs.rs/vach"

[dependencies]
anyhow = "1.0.42"
ed25519-dalek = "1.0.1"
lz4_flex = "0.8.2"
rand = "0.7.0"
hashbrown = "0.11.2"
bitflags = "1.3.2"
