name: Publish to crates.io

on:
  push:
    branches: [ main ]
    tags:
      - v[0-9]+.*

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: crates.io release
    #if: github.repository-owner == 'zeskeertwee'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: stable
      - run: cargo publish -p vach --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p vach-cli --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
