# adapted from https://github.com/taiki-e/cargo-hack/blob/36d81056f726de19c5865930bee5679513fdf74a/.github/workflows/release.yml

name: release

permissions:
  # TODO: once `releases: write` is supported, use it instead.
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: create github & crates.io release
    #if: github.repository-owner == 'zeskeertwee'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: nightly
      - run: cargo package -p vach
      - run: cargo package -p vach-cli
      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo publish -p vach --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: cargo publish -p vach-cli --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  upload-binaries:
    name: upload-${{ matrix.target }}
    #if: github.repository-owner == 'zeskeertwee'
    needs:
      - create-release
    strategy:
      matrix:
        include:
          # linux x86
          - target: x86_64-unknown-linux-gnu
          
          # windows x86
          - target: x86_64-pc-windows-gnu
            os: windows-latest

          # apple x86
          - target: x86_64-apple-darwin
            os: macos-latest

          # linux arm64
          - target: aarch64-unknown-linux-gnu

          # apple silicon (arm64)
          - target: aarch64-apple-darwin
            os: macos-latest


    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: nightly
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: vach-cli
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
