name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Build simple vach targets
      run: cargo test --package vach --lib --all-features -- tests::tests::builder_with_signature --exact --nocapture
    - name: Build signed vach targets
      run: cargo test --package vach --lib --all-features -- tests::tests::builder_no_signature --exact --nocapture
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
