name: Rust Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cli-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Change directory into cli directory
        run: cd vach-cli/test_data
      - name: List what directory we are in
        run: pwd && ls .
      - name: Give executive permissions to test script
        run: chmod +x test.sh
      - name: Run CLI tests
        run: sh test.sh
